version: '3.8'

services:
  con-service-2-db:
    build: ./con-service-2-db
    container_name: con-service-2-db
    ports:
      - "8001:8001"
      
  con-service-1:
    build: ./con-service-1
    container_name: con-service-1
    ports:
      - "8000:8000"
    depends_on:
      - con-service-2-db   